#!/usr/bin/env bash

now=$(date)
echo "$now: network check"

# 1) Check to see if ethernet is UP and get ip address
if [ -f /sys/class/net/eth0/carrier ]
then
    eth0status=$(cat /sys/class/net/eth0/carrier)
    eth0ip=$(ip addr show eth0 | grep -Po 'inet \K[\d.]+')
    echo "- eth0 active ($eth0ip)"
else
    eth0status=0
fi

# 2) Check to see if access point is UP and get ip address
if [ -f /sys/class/net/ap0/carrier ]
then
    ap0status=$(cat /sys/class/net/ap0/carrier)
    ap0ip=$(ip addr show ap0 | grep -Po 'inet \K[\d.]+')
    echo "- ap0 active ($ap0ip)"
else
    ap0status=0
fi

# 3) Check to see if wlan0 is UP and get ip address
if [ -f /sys/class/net/wlan0/carrier ]
then
    wlan0status=$(cat /sys/class/net/wlan0/carrier)
    wlan0ip=$(ip addr show wlan0 | grep -Po 'inet \K[\d.]+')
    echo "- wlan0 active ($wlan0ip)"
else
    wlan0status=0
fi

echo "eth0status=$eth0status"
echo "ap0status=$ap0status"
echo "wlan0status=$wlan0status"